### ISSUE TITLE
Trying to use the old ports

### ISSUE THREAD

**Issue by 3pdev-alex** [localstack/awscli-local#39]
I posted this [in the LocalStack issues](https://github.com/localstack/localstack/issues/3673) as well, but realized it may be an awscli-local issue. Once I changed my docker setup to use LocalStack 0.12.7 my awslocal command is still trying to connect using the old (and deprecated) port numbers. Here's my docker service:

```yml
  localstack:
    image: localstack/localstack:0.12.7
    restart: always
    ports:
      - 4566:4566
      - 8080:8080
    environment:
      - DOCKER_HOST=unix.///var/run/docker.sock
      - DEFAULT_REGION=us-east-1
      - DEBUG=1
      - PORT_WEB_UI=8080
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - ${LOG_ROOT}/localstack/:/tmp/localstack
      - /var/run/docker.sock:/var/run/docker.sock
      - ./localstack/startup/:/docker-entrypoint-initaws.d
    networks:
      - myNetwork
```

Using this, I get `Could not connect to the endpoint URL: "http://localhost:4576/"`. If I change my ports to "4566-4599:4566-4599" I get `Connection was closed before we received a valid response from endpoint URL: "http://localhost:4576/"`. What's the secret to using port 4566?
