### ISSUE TITLE
Specifying `--endpoint-url` gets an "Unable to find LocalStack endpoint for service" error 

### ISSUE THREAD

**Issue by niauah** [localstack/awscli-local#51]
I was running a seperate testing Localstack host that exposes different ports with the `docker-compose` file like this:
```yml
version: "3.8"

services:
  localstack-testing:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_testing}"
    image: localstack/localstack
    ports:
      - "127.0.0.1:5510-5559:4510-4559"  # <--Port number changed here
      - "127.0.0.1:5566:4566"            # <--Port number changed here
    environment:
      - LOCALSTACK_SERVICES=${SERVICES-}
      - DEBUG=${DEBUG-}
      - DATA_DIR=${DATA_DIR-}
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR-}
      - HOST_TMP_FOLDER=${TMPDIR:-/tmp/}localstack
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${TMPDIR:-/tmp}/localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
```

The Localstack service was started by `docker-compose up` command and went up normally.

When I tried the `awslocal --endpoint-url http://localhost:5566/ help` command, an error occured:
`ERROR: Unable to find LocalStack endpoint for service "http://localhost:5566/"`

However, when using `aws` instead of `awslocal`, the command was successfully executed and the help message was shown.

If any extra information is needed to reproduce the situation, please let me know.
