### ISSUE TITLE
"Unable to locate credentials" while using awslocal

### ISSUE THREAD

**Issue by bobbui** [localstack/awscli-local#85]
i have localstack running from docker compose yaml as follow:
```yaml
version: "3.8"

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-main}"
    image: localstack/localstack
    ports:
      - "4566:4566"            # LocalStack Gateway
      - "4510-4559:4510-4559"  # external services port range
    environment:
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      - DEBUG=${DEBUG:-1}
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    network_mode: bridge
```
I also run ``aws configure` as instructed here: https://github.com/localstack/localstack/issues/8424#issuecomment-1573660002
also set environment variable AWS_ENDPOINT_URL=http://localhost:4566 without any success.

but when I run a sample command. e.g: `awslocal s3 ls` it still ask for the credential as follow:
```
Unable to locate credentials. You can configure credentials by running "aws configure".
```
I check homedir/.aws, **config** and **credentials** file is properly setup,
**config**
```
[default]
region = us-east-1
````
**credentials**
```
[default]
aws_access_key_id = test
aws_secret_access_key = test
```

running AWS CLI with endpoint parameter works though 
```
# all of these works
aws --endpoint-url=http://localhost:4566 s3 ls
aws  kinesis list-streams --region eu-central-1  --endpoint-url=http://localhost:4566
aws  s3 ls
aws  kinesis list-streams --region eu-central-1 
```

Environment:
- windows 11
- aws --version
aws-cli/2.17.27 Python/3.11.9 Windows/10 exe/AMD64
-localstack --version
3.6.0
- awslocal latest version 

Please suggest how I can get around this issue.

Thanks in advance
